application: alsproyect-creak
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /templates
  static_dir: templates
  application_readable: true

- url: /src
  static_dir: src
  application_readable: true

- url: /res
  static_dir: res

- url: /css
  static_dir: css
  application_readable: true

- url: /user/register
  script: handlers.user.register.app

- url: /welcome
  script: handlers.welcome.app

- url: /creak/addcreak
  script: handlers.creak.addcreak.app

- url: /creak/showcreak
  script: handlers.creak.showcreak.app

- url: /user/showusers
  script: handlers.user.showusers.app

- url: /user/profile
  script: handlers.user.profile.app

- url: /followandfollowers/followuser
  script: handlers.followandfollowers.followuser.app

- url: /followandfollowers/showfollows
  script: handlers.followandfollowers.showfollows.app

- url: /followandfollowers/showfollowers
  script: handlers.followandfollowers.showfollowers.app

- url: /creak/deletecreak
  script: handlers.creak.deletecreak.app

- url: /creak/recreak
  script: handlers.creak.recreak.app

- url: /creak/likecreak
  script: handlers.creak.likecreak.app

- url: /creak/deletelikecreak
  script: handlers.creak.deletelikecreak.app

- url: /creak/showlikes
  script: handlers.creak.showlikes.app

- url: /notification/shownotifications
  script: handlers.notification.shownotifications.app

- url: /notification/deletenotification
  script: handlers.notification.deletenotification.app

- url: .*
  script: handlers.main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "latest"
