application: cutre-libro-visitas
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /templates
  static_dir: templates
  application_readable: true

- url: /src
  static_dir: src
  application_readable: true

- url: /res
  static_dir: res

- url: /css
  static_dir: css
  application_readable: true

- url: /register
  script: handlers.register.app

- url: /welcome
  script: handlers.welcome.app

- url: /addcreak
  script: handlers.addcreak.app

- url: /showcreak
  script: handlers.showcreak.app

- url: /showusers
  script: handlers.showusers.app

- url: /profile
  script: handlers.profile.app

- url: /followuser
  script: handlers.followuser.app

- url: /showfollows
  script: handlers.showfollows.app

- url: /showfollowers
  script: handlers.showfollowers.app

- url: /deletecreak
  script: handlers.deletecreak.app

- url: /recreak
  script: handlers.recreak.app

- url: /likecreak
  script: handlers.likecreak.app

- url: /deletelikecreak
  script: handlers.deletelikecreak.app

- url: /showlikes
  script: handlers.showlikes.app

- url: .*
  script: handlers.main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "latest"
